### ISSUE TITLE
macOS Catalina: probably needs bitcoin rebase  

### ISSUE THREAD

**Issue by Sjors** [bitcoinops/taproot-workshop#163]
When trying to compile the Taproot_V0.1.4 branch on macOS Catalina I get:

```
qt/macdockiconhandler.mm:24:14: error: no matching function for call to 'objc_msgSend'
    id app = objc_msgSend((id)objc_getClass("NSApplication"), sel_registerName("sharedApplication"));
             ^~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/objc/message.h:63:1: note: candidate function not viable:
      requires 0 arguments, but 2 were provided
objc_msgSend(void /* id self, SEL op, ... */ )
```

These issues have been patched on master since: https://github.com/bitcoin/bitcoin/issues/16387

@jnewbery's work in progress branch Taproot_V0.1.5-proposed  doesn't have this problem, as it's based on a more recent master.

Unfortunately for myself, I'm unable to compile versions of Bitcoin Core that still depend on OpenSSL, probably due to a local issue.  Rebasing to the most recent version of master isn't easy either, because the taproot branch is behind. I'll figure something out...

**Comment by elichai** [comment]
@Sjors `Taproot_V0.1.5-proposed` is based on the 32byte keys. so it won't work with current version of the workshop.

**Comment by Sjors** [comment]
Ok, I'll stick to workshop version 0.14. Cherry-picking the from #16720 makes the error go away too.

```
git cherry-pick 0bb33b5348dbddd65b88a7f00449c965562355d3
```

As for the RNG compile error I ran into, either the downgrade, or removing homebrew's openssl did the trick (less drastic solution might be to point `./configure` to the system version).

**Comment by pavel-bc** [comment]
@Sjors Thanks Sjors, that helped a lot! 

For future readers - I've also had issues with compiling modified `secp256k1` with Schnorr signatures support in this repo, because I had globally installed default version of `libsecp256k1` via Homebrew. So uninstalling last one helped
